apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_SETTINGS_MODULE: tech.settings
  CELERY_BROKER_URL: "amqp://admin:password@rabbitmq.default.svc.cluster.local:5672//"
  CELERY_RESULT_BACKEND: django-db
  ALLOWED_HOST: '0.0.0.0'
